### ISSUE TITLE
Oauth (via socialite)

### ISSUE THREAD

**Issue by Boy132** [pelican-dev/panel#385]
https://laravel.com/docs/11.x/socialite
https://socialiteproviders.com/

- [x] Backend (#386)
- [x] Frontend (#718 & #416)
- [x] Add more providers (e.g. authentik, google, microsoft, steam) (#718)
- [x] Make it easier to add additional providers (without code edit) (#718)
- [x] Make OAuth settings configurable via panel UI (#839)

**Comment by KeySC07** [comment]
Would be nice to see an option for JIT(Just-In-Time) provisioning added to create users upon sign-in via SSO.

**Comment by timoschirmer** [comment]
Would love to see support for authentik or some kind of generic oauth2 provider in the future.

**Comment by KeySC07** [comment]
> Would love to see support for authentik or some kind of generic oauth2 provider in the future.

Authentik is already supported see here https://socialiteproviders.com/Authentik/#installation-basic-usage
just gotta make some changes to get it working.

**Comment by andyondrya** [comment]
Weird migration error,
```bash

   INFO  Running migrations.  

  2024_06_13_120409_add_oauth_column_to_users .............................................................................. 1.30ms FAIL

In Connection.php line 813:
                                                                                                                                         
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (Connection: sqlite, SQL: alter table "users"   
  add column "oauth" text not null)                                                                                                      
                                                                                                                                         

In Connection.php line 571:
                                                                                          
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

**Comment by RMartinOscar** [comment]
> Weird migration error,
> 
> ```shell
>    INFO  Running migrations.  
> 
>   2024_06_13_120409_add_oauth_column_to_users .............................................................................. 1.30ms FAIL
> 
> In Connection.php line 813:
>                                                                                                                                          
>   SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (Connection: sqlite, SQL: alter table "users"   
>   add column "oauth" text not null)                                                                                                      
>                                                                                                                                          
> 
> In Connection.php line 571:
>                                                                                           
>   SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
> ```

Fixed in [PR #409](https://github.com/pelican-dev/panel/pull/409)

**Comment by KeySC07** [comment]
Would be nice to see enforce MFA as an option as well.

Using the amr attribute within the OAuth token contains the types auth the user has completed
at the identity provider, an example:
    "amr": [
        "pwd",
        "mfa"
    ],
    
You could use this to add an option to enforce MFA which would deny the login if the amr token doesn't contain "mfa".

**Comment by phoenix-limited** [comment]
> > Would love to see support for authentik or some kind of generic oauth2 provider in the future.
> 
> Authentik is already supported see here https://socialiteproviders.com/Authentik/#installation-basic-usage just gotta make some changes to get it working.

I've followed the couple things listed there, what else needs done to enable logging in with authentik? I'm really not seeing anything else for it

**Comment by Boy132** [comment]
> > > Would love to see support for authentik or some kind of generic oauth2 provider in the future.
> > 
> > 
> > Authentik is already supported see here https://socialiteproviders.com/Authentik/#installation-basic-usage just gotta make some changes to get it working.
> 
> I've followed the couple things listed there, what else needs done to enable logging in with authentik? I'm really not seeing anything else for it

Currently only the backend for oauth works, there is no frontend yet. So you can't use it yet.

**Comment by phoenix-limited** [comment]
> Currently only the backend for oauth works, there is no frontend yet. So you can't use it yet.

I see. Would love to get this working, but I doubt I'll be of any help. I'll happily be a test-bed when time come though

**Comment by Felitendo** [comment]
Is there a way to use OIDC/Oauth2 as of now even without the configuration settings UI?

**Comment by phoenix-limited** [comment]
I also have this working this way. If we could, it would be nice to define some scopes (like for groups/role claim/auto user linking). Fantastic for internal use for now!
